### PR TITLE
Updating the schedule due to the change in weeks we're starting FPGA bootcamp

### PR DESCRIPTION
**Pull request by JakeEdvenson**
I received a message today that we'd be starting FPGA bootcamp next week, so this is a revised schedule reflecting this change.

### CODE REVIEW

**Review by jgoeders — APPROVED** [review]

**Comment by JakeEdvenson** [comment]
It says that only those with write access to this repository can merge pull requests, so it wont let me resolve the conflicts.

**Comment by jgoeders** [comment]
In this case you don't resolve the conflict using github, you resolve it locally using git:
1. Run git fetch
1. Merge in changes from main that you are missing: `git merge origin/main`
1. Resolve conflict locally.
1. Push up changes to this branch to fix this PR.

**Comment by JakeEdvenson** [comment]
So, I followed these steps and the conflicts are still showing up. Any other ideas?

**Comment by jgoeders** [comment]
@JakeEdvenson Doesn't look like the merge got resolved properly.  I see new and old entries in the table.

**Comment by JakeEdvenson** [comment]
The table should be fixed, I'm not sure what the errors are that are popping up now in the checks.

**Comment by jgoeders** [comment]
@JakeEdvenson  Don't worry about the errors in the checks...but it's now showing 0 files changed.  So somehow you lost your changes.

**Comment by JakeEdvenson** [comment]
Sorry about that! I don't know why github was giving me so much trouble on this! Thank you!

**Pull request merged**
